### ISSUE TITLE
Import name

### ISSUE THREAD

**Issue by spencems** [DotNetIT/EpicorDMTScripts#1]
When i try to use the import for a - Sales Order Line Misc Charge - i get the attached error.

i assume this is a spacing issue with the import tag
![capture](https://cloud.githubusercontent.com/assets/10678469/16386565/08ce96da-3c89-11e6-8d45-8d51347b5fd0.JPG)

has anyone else had this issue when using an import with spaces?

**Comment by ArthurACole** [comment]
Please note that when using Windows PowerShell, the name of an Import that includes spaces needs to be enclosed in quotation marks which are escaped with the backtick (`).  
E.g.
-ArgumentList "-User $User -Pass $Pass -Add -Update -Import `"Sales Order Detail`" -Source $Source -ConfigValue $ConfigFile"

Regards
Arthur

**Comment by ArthurACole** [comment]
Please note that when using Windows PowerShell, the name of an Import that includes spaces needs to be enclosed in quotation marks which are escaped with the backtick

[Imports with spaces in name.txt](https://github.com/DotNetIT/EpicorDMTScripts/files/336548/Imports.with.spaces.in.name.txt)

**Comment by spencems** [comment]
excellent, thanks Arthur. tested and works.
